// 389. Find the Difference
// Easy
// Topics
// premium lock icon
// Companies
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.


// two strings -> s and t ->t is formed by the random suffling of characters of string s and adding one more char at random position
// s,t -> both are in lower cases, s can be empty, length of t always one more than s 

//return the added char to t

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    if(s.length===0) return t
    let map = new Map()

    for(let ch of s){
        map.set(ch, (map.get(ch)||0)+1)
    }
    for(let ch of t){
        if(!map.has(ch) ||( map.get(ch)===0)){
            return ch
        }
        map.set(ch, (map.get(ch))-1)
    }
};

//test cases
console.log(findTheDifference('abcd', 'abcde'),'e')
console.log(findTheDifference('','y'),'y')